todoproject/todoapp/urls.py
from django.urls import path, include
from . import views
app_name='todoapp'

urlpatterns = [
    path('', views.add, name='home'),
    path('delete/<int:task_id>/',views.delete,name='delete'),
    path('update/<int:id>/',views.update,name='update'),
    path('cbvhome/',views.Tasklistview.as_view(),name='cbvhome'),
    path('cbvdetails/<int:pk>/',views.TaskDetailview.as_view(),name='cbvdetails'),
    path('cbvedit/<int:pk>/',views.Taskupdateview.as_view(),name='cbvedit'),
    path('cbvdelete/<int:pk>/',views.TaskDeleteView.as_view(),name='cbvdelete'),

]

todoproject/todoproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("todoapp.urls"))
]

if settings.DEBUG :
    urlpatterns +=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns +=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

todoproject/todoapp/models.py
from django.db import models
from django.utils import timezone


# Create your models here.
class task(models.Model):
    name=models.CharField(max_length=250)
    priority=models.CharField(max_length=250)
    date=models.DateField(default=timezone.now)

    def __str__(self):
        return self.name

todoproject/todoapp/forms.py
from . models import task
from django import forms

class TodoForm(forms.ModelForm):
    class Meta:
        model=task
        fields=['name','priority','date']

todoproject/todoapp/views.py
from django.http import HttpResponse
from django.shortcuts import render,redirect
from django.urls import reverse_lazy

from . models import task
from .forms import TodoForm
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import UpdateView,DeleteView

def add(request):
    Task1 = task.objects.all()
    if request.method=='POST':
        name=request.POST.get('task','')
        priority=request.POST.get('priority','')
        date=request.POST.get('date','')
        Task=task(name=name,priority=priority)
        Task.save()
    return render(request, "home.html",{'Task':Task1})

def delete(request,task_id):
    Task=task.objects.get(id=task_id)
    if request.method=='POST':
        Task.delete()
        return redirect('/')
    return render(request,'delete.html')

def update(request,id):
    Task=task.objects.get(id=id)
    form=TodoForm(request.POST or None , instance=Task)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request,'update.html',{'form':form,'Task':Task})


class Tasklistview(ListView):
    model = task
    template_name = 'home.html'
    context_object_name = 'Task'

class TaskDetailview(DetailView):
    model = task
    template_name = 'details.html'
    context_object_name = 'task'

class Taskupdateview(UpdateView):
    model= task
    template_name= 'edit.html'
    context_object_name = 'task'
    fields = ('name','priority','date')

    def get_success_url(self):
        return reverse_lazy('todoapp:cbvdetails',kwargs={'pk':self.object.id})

class TaskDeleteView(DeleteView):
    model = task
    template_name = 'delete.html'
    success_url = reverse_lazy('todoapp:cbvhome')

todoproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>PROFILE PAGE</title>

    <link rel="stylesheet"  href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">

</head>
<body>

{% block body %}
{% endblock %}
</body>
</html>

todoproject/templates/delete.html
{% extends 'base.html' %}
{% block body %}
<form method="POST">
    {% csrf_token %}
    Are you sure Done This Task?
    <input type="submit" class="btn btn-danger" value="YES">
</form>
{% endblock %}

todoproject/templates/details.html
{% extends 'base.html' %}
{% block body %}

 <div class="shadow card">
                <div class="card-body">
                    <h5 class="card-title">{{ task.name }}:</h5>
                    <p><b>{{ task.priority }}</b></p>
                    <p><b>{{ task.date }}</b></p>
                    <a class="btn btn-danger" href="{% url 'todoapp:delete' task.id %}">DONE</a>
                    <a class="btn btn-primary" href="{% url 'todoapp:update' task.id %}">UPDATE</a>
                </div>
            </div>
            <br>

{% endblock %}

todoproject/templates/edit.html
{% extends 'base.html' %}
{% block body %}

<div class="card">
    <div class="card-header">
        <div class="card-title">
             UPDATED TASK
        </div>
        <div class="card-body">
            <form method="POST">
                {% csrf_token %}
                {{form.as_p}}
                <input type="submit" class="btn btn-success" value="UPDATE">
            </form>
        </div>
    </div>
</div>


{% endblock %}

todoproject/templates/home.html
{% extends 'base.html' %}
{% block body %}

<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <div class="banner">
                <div class="banner-text">
                    <h1>TODO</h1>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="container">
    <div class="row">
        <div class="col-md-6">
            <form method="POST" class="p-3 shadow">
            {% csrf_token %}
            <div class="form-group">
                <input type="text" name="task" placeholder="ENTER TASK">
            </div>
            <div class="form-group">
                <input type="text" name="priority" placeholder="ENTER PRIORITY">
            </div>
            <div class="form-group">
                <input type="date" name="date" placeholder="DATE">
            </div>
                <input type="submit" value="SUBMIT" class="btn btn-success">
            </form>
        </div>

        <div class="col-md-6">
            <h3>Pending Tasks</h3>
             {% for i in Task %}
            <div class="shadow card">
                <div class="card-body">
                    <h5 class="card-title">{{ i.name }}:</h5>
                    <p><b>{{ i.priority }}</b></p>
                    <p><b>{{ i.date }}</b></p>
                    <a class="btn btn-danger" href="{% url 'todoapp:cbvdelete' i.id %}">DONE</a>
                    <a class="btn btn-primary" href="{% url 'todoapp:cbvedit' i.id %}">UPDATE</a>
                </div>
            </div>
            <br>
            {% endfor %}

        </div>
    </div>
</div>

{% endblock %}

todoproject/templates/update.html
{% extends 'base.html' %}
{% block body %}
<form method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" class="btn btn-success" value="UPDATE">
</form>
{% endblock %}